
libbounds-init c

dg-init

global srcdir
foreach flags [list {} {-O2} {-O3}] {
    foreach srcfile [lsort [glob -nocomplain \
                            ${srcdir}/libbounds.c/pass*.c \
                            ${srcdir}/libbounds.c/fail*.c \
                            ${srcdir}/libbounds.c/heap/pass*.c \
                            ${srcdir}/libbounds.c/heap/fail*.c]] {
	set bsrc [file tail $srcfile]
	dg-runtest $srcfile $flags "-fbounds-checking -lbounds"
    }
}

dg-finish
