#!/bin/bash
#@!  -*- buffer-read-only: t -*- vi: set ro:
#@#@# 
#@#@# DO NOT EDIT THIS FILE   (melt-build-script.sh)
#@#@# 
#@#@# It has been AutoGen-ed  July 16, 2012 at 04:41:46 PM by AutoGen 5.16
#@#@# From the definitions    melt-build-script.def
#@#@# and the template file   melt-build-script.tpl
# Generated shell script for MELT modules and MELT translator bootstrap
#   Copyright (C) 2012  Free Software Foundation
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
#@ from melt-build-script.tpl line 20 generated by Autogen 5.16 using melt-build-script.def




## source the parameters  melt-build-script.tpl:27/1
. ./melt-build-param.sh

export GAWK=${GAWK:=gawk}

## our error function  melt-build-script.tpl:32/2
function meltbuild_error () {
    echo MELT BUILD SCRIPT FAILURE: $@ > /dev/stderr
    exit 1
}

## symbolic linking
function meltbuild_symlink () {
    ln -svf `realpath $1` $2
}

## our info function
function meltbuild_info () {
    echo MELT BUILD SCRIPT INFO: $@ > /dev/stderr
}

function meltbuild_emit () {
    local meltfrom=$1
    local meltmode=$2
    local meltoutput=$3
    local meltsource=$4
    local meltinit=$5
}

GCCMELT_ZERO_FLAVOR=${GCCMELT_STAGE_ZERO#melt-stage0-}

## The base name of the MELT translator files melt-build-script.tpl:58/3
GCCMELT_TRANSLATOR_BASE=(  warmelt-first \
  warmelt-base \
  warmelt-debug \
  warmelt-macro \
  warmelt-normal \
  warmelt-normatch \
  warmelt-genobj \
  warmelt-outobj \
  warmelt-modes )

case $GCCMELT_ZERO_FLAVOR in
    optimized) ;;
    dynamic) ;;
    debugnoline) ;;
    quicklybuilt) ;;
    *) meltbuild_error  melt-build-script.tpl:66/4 bad zero flavor $GCCMELT_ZERO_FLAVOR ;;
esac

[ -d melt-workdir ] || mkdir  melt-workdir

## our stage0 melt-build-script.tpl:71/5

[ -d $GCCMELT_STAGE_ZERO ] || mkdir  $GCCMELT_STAGE_ZERO



meltbuild_info making stage0 warmelt-first  melt-build-script.tpl:77/6

##  stage0 melt-build-script.tpl:79/7 symlink descriptor file warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/8 symlink source code warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/9 symlink stamp warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_FIRST_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/10 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-first \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_FIRST_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-first \
 || meltbuild_error  melt-build-script.tpl:107/11 stage0 warmelt-first did not build

meltbuild_info melt-build-script.tpl:109/12 successfully build stage0 warmelt-first


meltbuild_info making stage0 warmelt-base  melt-build-script.tpl:77/13

##  stage0 melt-build-script.tpl:79/14 symlink descriptor file warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/15 symlink source code warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/16 symlink stamp warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_BASE_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/17 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-base \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_BASE_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-base \
 || meltbuild_error  melt-build-script.tpl:107/18 stage0 warmelt-base did not build

meltbuild_info melt-build-script.tpl:109/19 successfully build stage0 warmelt-base


meltbuild_info making stage0 warmelt-debug  melt-build-script.tpl:77/20

##  stage0 melt-build-script.tpl:79/21 symlink descriptor file warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/22 symlink source code warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/23 symlink stamp warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_DEBUG_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/24 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-debug \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_DEBUG_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-debug \
 || meltbuild_error  melt-build-script.tpl:107/25 stage0 warmelt-debug did not build

meltbuild_info melt-build-script.tpl:109/26 successfully build stage0 warmelt-debug


meltbuild_info making stage0 warmelt-macro  melt-build-script.tpl:77/27

##  stage0 melt-build-script.tpl:79/28 symlink descriptor file warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/29 symlink source code warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/30 symlink stamp warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_MACRO_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/31 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-macro \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_MACRO_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-macro \
 || meltbuild_error  melt-build-script.tpl:107/32 stage0 warmelt-macro did not build

meltbuild_info melt-build-script.tpl:109/33 successfully build stage0 warmelt-macro


meltbuild_info making stage0 warmelt-normal  melt-build-script.tpl:77/34

##  stage0 melt-build-script.tpl:79/35 symlink descriptor file warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/36 symlink source code warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/37 symlink stamp warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_NORMAL_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/38 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-normal \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_NORMAL_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-normal \
 || meltbuild_error  melt-build-script.tpl:107/39 stage0 warmelt-normal did not build

meltbuild_info melt-build-script.tpl:109/40 successfully build stage0 warmelt-normal


meltbuild_info making stage0 warmelt-normatch  melt-build-script.tpl:77/41

##  stage0 melt-build-script.tpl:79/42 symlink descriptor file warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/43 symlink source code warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/44 symlink stamp warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_NORMATCH_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/45 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_NORMATCH_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-normatch \
 || meltbuild_error  melt-build-script.tpl:107/46 stage0 warmelt-normatch did not build

meltbuild_info melt-build-script.tpl:109/47 successfully build stage0 warmelt-normatch


meltbuild_info making stage0 warmelt-genobj  melt-build-script.tpl:77/48

##  stage0 melt-build-script.tpl:79/49 symlink descriptor file warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/50 symlink source code warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/51 symlink stamp warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_GENOBJ_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/52 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_GENOBJ_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-genobj \
 || meltbuild_error  melt-build-script.tpl:107/53 stage0 warmelt-genobj did not build

meltbuild_info melt-build-script.tpl:109/54 successfully build stage0 warmelt-genobj


meltbuild_info making stage0 warmelt-outobj  melt-build-script.tpl:77/55

##  stage0 melt-build-script.tpl:79/56 symlink descriptor file warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/57 symlink source code warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/58 symlink stamp warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/59 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-outobj \
 || meltbuild_error  melt-build-script.tpl:107/60 stage0 warmelt-outobj did not build

meltbuild_info melt-build-script.tpl:109/61 successfully build stage0 warmelt-outobj


meltbuild_info making stage0 warmelt-modes  melt-build-script.tpl:77/62

##  stage0 melt-build-script.tpl:79/63 symlink descriptor file warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:84/64 symlink source code warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:92/65 symlink stamp warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_MODES_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:100/66 \
   GCCMELT_MODULE_WORKSPACE=melt-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-modes \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_MODES_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-modes \
 || meltbuild_error  melt-build-script.tpl:107/67 stage0 warmelt-modes did not build

meltbuild_info melt-build-script.tpl:109/68 successfully build stage0 warmelt-modes




################################################################
################################################################
#################@ before our stages melt-build-script.tpl:116/69 



#@  begin for meltbuild-stage1 melt-build-script.tpl:120/70

[ -d meltbuild-stage1 ] || mkdir meltbuild-stage1

#### rules for meltbuild-stage1, previous $(MELT_STAGE_ZERO) melt-build-script.tpl:129/71



### the C source of meltbuild-stage1 for warmelt-first melt-build-script.tpl:134/72
#@ melt-build-script.tpl:135/73 base warmelt-first stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/74 
#@ melt-build-script.tpl:138/75 end base warmelt-first stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-base melt-build-script.tpl:134/76
#@ melt-build-script.tpl:135/77 base warmelt-base stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/78 
#@ melt-build-script.tpl:138/79 end base warmelt-base stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-debug melt-build-script.tpl:134/80
#@ melt-build-script.tpl:135/81 base warmelt-debug stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/82 
#@ melt-build-script.tpl:138/83 end base warmelt-debug stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-macro melt-build-script.tpl:134/84
#@ melt-build-script.tpl:135/85 base warmelt-macro stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/86 
#@ melt-build-script.tpl:138/87 end base warmelt-macro stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-normal melt-build-script.tpl:134/88
#@ melt-build-script.tpl:135/89 base warmelt-normal stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/90 
#@ melt-build-script.tpl:138/91 end base warmelt-normal stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-normatch melt-build-script.tpl:134/92
#@ melt-build-script.tpl:135/93 base warmelt-normatch stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/94 
#@ melt-build-script.tpl:138/95 end base warmelt-normatch stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-genobj melt-build-script.tpl:134/96
#@ melt-build-script.tpl:135/97 base warmelt-genobj stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/98 
#@ melt-build-script.tpl:138/99 end base warmelt-genobj stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-outobj melt-build-script.tpl:134/100
#@ melt-build-script.tpl:135/101 base warmelt-outobj stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/102 
#@ melt-build-script.tpl:138/103 end base warmelt-outobj stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-modes melt-build-script.tpl:134/104
#@ melt-build-script.tpl:135/105 base warmelt-modes stage meltbuild-stage1 prevstage $(MELT_STAGE_ZERO) prevflavor  $(MELT_ZERO_FLAVOR) 

meltbuild_emit melt-build-script.tpl:137/106 
#@ melt-build-script.tpl:138/107 end base warmelt-modes stage meltbuild-stage1 



########@  end for meltbuild-stage1 melt-build-script.tpl:142/108

#@  begin for meltbuild-stage2 melt-build-script.tpl:120/109

[ -d meltbuild-stage2 ] || mkdir meltbuild-stage2

#### rules for meltbuild-stage2, previous meltbuild-stage1 melt-build-script.tpl:129/110



### the C source of meltbuild-stage2 for warmelt-first melt-build-script.tpl:134/111
#@ melt-build-script.tpl:135/112 base warmelt-first stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/113 
#@ melt-build-script.tpl:138/114 end base warmelt-first stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-base melt-build-script.tpl:134/115
#@ melt-build-script.tpl:135/116 base warmelt-base stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/117 
#@ melt-build-script.tpl:138/118 end base warmelt-base stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-debug melt-build-script.tpl:134/119
#@ melt-build-script.tpl:135/120 base warmelt-debug stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/121 
#@ melt-build-script.tpl:138/122 end base warmelt-debug stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-macro melt-build-script.tpl:134/123
#@ melt-build-script.tpl:135/124 base warmelt-macro stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/125 
#@ melt-build-script.tpl:138/126 end base warmelt-macro stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-normal melt-build-script.tpl:134/127
#@ melt-build-script.tpl:135/128 base warmelt-normal stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/129 
#@ melt-build-script.tpl:138/130 end base warmelt-normal stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-normatch melt-build-script.tpl:134/131
#@ melt-build-script.tpl:135/132 base warmelt-normatch stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/133 
#@ melt-build-script.tpl:138/134 end base warmelt-normatch stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-genobj melt-build-script.tpl:134/135
#@ melt-build-script.tpl:135/136 base warmelt-genobj stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/137 
#@ melt-build-script.tpl:138/138 end base warmelt-genobj stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-outobj melt-build-script.tpl:134/139
#@ melt-build-script.tpl:135/140 base warmelt-outobj stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/141 
#@ melt-build-script.tpl:138/142 end base warmelt-outobj stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-modes melt-build-script.tpl:134/143
#@ melt-build-script.tpl:135/144 base warmelt-modes stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/145 
#@ melt-build-script.tpl:138/146 end base warmelt-modes stage meltbuild-stage2 



########@  end for meltbuild-stage2 melt-build-script.tpl:142/147

#@  begin for meltbuild-stage3 melt-build-script.tpl:120/148

[ -d meltbuild-stage3 ] || mkdir meltbuild-stage3

#### rules for meltbuild-stage3, previous meltbuild-stage2 melt-build-script.tpl:129/149



### the C source of meltbuild-stage3 for warmelt-first melt-build-script.tpl:134/150
#@ melt-build-script.tpl:135/151 base warmelt-first stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/152 
#@ melt-build-script.tpl:138/153 end base warmelt-first stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-base melt-build-script.tpl:134/154
#@ melt-build-script.tpl:135/155 base warmelt-base stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/156 
#@ melt-build-script.tpl:138/157 end base warmelt-base stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-debug melt-build-script.tpl:134/158
#@ melt-build-script.tpl:135/159 base warmelt-debug stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/160 
#@ melt-build-script.tpl:138/161 end base warmelt-debug stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-macro melt-build-script.tpl:134/162
#@ melt-build-script.tpl:135/163 base warmelt-macro stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/164 
#@ melt-build-script.tpl:138/165 end base warmelt-macro stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-normal melt-build-script.tpl:134/166
#@ melt-build-script.tpl:135/167 base warmelt-normal stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/168 
#@ melt-build-script.tpl:138/169 end base warmelt-normal stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-normatch melt-build-script.tpl:134/170
#@ melt-build-script.tpl:135/171 base warmelt-normatch stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/172 
#@ melt-build-script.tpl:138/173 end base warmelt-normatch stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-genobj melt-build-script.tpl:134/174
#@ melt-build-script.tpl:135/175 base warmelt-genobj stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/176 
#@ melt-build-script.tpl:138/177 end base warmelt-genobj stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-outobj melt-build-script.tpl:134/178
#@ melt-build-script.tpl:135/179 base warmelt-outobj stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/180 
#@ melt-build-script.tpl:138/181 end base warmelt-outobj stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-modes melt-build-script.tpl:134/182
#@ melt-build-script.tpl:135/183 base warmelt-modes stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_emit melt-build-script.tpl:137/184 
#@ melt-build-script.tpl:138/185 end base warmelt-modes stage meltbuild-stage3 



########@  end for meltbuild-stage3 melt-build-script.tpl:142/186



################
meltbuild_info melt-build-script.tpl:147/187 successfully done
#@ eof melt-build-script.tpl:148/188 end of generated melt-build-script.sh
