#!/bin/bash
#@!  -*- buffer-read-only: t -*- vi: set ro:
#@#@# 
#@#@# DO NOT EDIT THIS FILE   (melt-build-script.sh)
#@#@# 
#@#@# It has been AutoGen-ed  July 17, 2012 at 04:44:05 PM by AutoGen 5.16
#@#@# From the definitions    melt-build-script.def
#@#@# and the template file   melt-build-script.tpl
# Generated shell script for MELT modules and MELT translator bootstrap
#   Copyright (C) 2012  Free Software Foundation
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
#@ from melt-build-script.tpl line 20 generated by Autogen 5.16 using melt-build-script.def




## source the parameters  melt-build-script.tpl:27/1
. ./melt-build-param.sh

export GAWK=${GAWK:=gawk}
export MD5SUM=${MD5SUM:=md5sum}
export GCCMELT_STAGE

date +"/*empty file for MELT build %c*/" > meltbuild-empty-file.c

[ -d meltbuild-workdir ] || mkdir  meltbuild-workdir

## our error function  melt-build-script.tpl:38/2
function meltbuild_error () {
    echo MELT BUILD SCRIPT FAILURE: $@ > /dev/stderr
    exit 1
}

## symbolic linking
function meltbuild_symlink () {
    ln -svf `realpath $1` $2
}

## our info function
function meltbuild_info () {
    echo MELT BUILD SCRIPT INFO: $@ > /dev/stderr
}

## utility to build MELT specific arguments in meltbuild_emit
function meltbuild_arg () {
    local meltarg=$1
    if [ -z "$GCCMELT_IS_PLUGIN" ]; then
	echo " -fmelt-$meltarg"
    else
	echo " -fplugin-arg-melt-$meltarg"
    fi
}

## function to run MELT to emit C code
function meltbuild_emit () {
    local meltfrom=$1
    local meltmode=$2
    local meltbase=$3
    local meltstage=$4
    local meltprevstage=$5
    local meltinit=$6
    local meltinclude=$7
    local meltargs=$meltstage/$meltbase.args
    local meltsrc=$(realpath $GCCMELT_MELTSOURCEDIR/$meltbase.melt)
    meltbuild_info meltfrom=$meltfrom meltmode=$meltmode meltbase=$meltbase meltstage=$meltstage meltprevstage=$meltprevstage meltinit=$meltinit meltinclude=$meltinclude meltsrc=$meltsrc
    local meltsum
    if [ -z "$meltmode" ]; then
	meltbuild_error $meltfrom no MELT mode at stage $meltstage
    fi
    if [ ! -f "$meltsrc" ]; then
	meltbuild_error $meltfrom no MELT file $meltsrc at stage $meltstage base $meltbase
    fi
    if [ -z "$meltinit" ]; then
	meltbuild_error $meltfrom no MELT init  at stage $meltstage base $meltbase
    fi
    meltsum=$($MD5SUM $meltsrc | $GAWK '{print $1}')
    meltbuild_info $meltfrom emit C code for $meltbase of $meltstage
    echo -Wno-shadow -frandom-seed=$meltsum > $meltargs-$$-tmp
    ## various arguments
    meltbuild_arg mode=$meltmode >> $meltargs-$$-tmp
    meltbuild_arg arg=$meltsrc >>  $meltargs-$$-tmp
    meltbuild_arg output=$meltstage/$meltbase  >>  $meltargs-$$-tmp
    meltbuild_arg "module-make-command='$GCCMELT_MAKE'" >> $meltargs-$$-tmp
    meltbuild_arg module-makefile=$GCCMELT_MODULE_MK >> $meltargs-$$-tmp
    meltbuild_arg "module-cflags='$GCCMELT_INCLUDES -I. -I$meltstage -I$meltprevstage $GCCMELT_COMPILER_FLAGS'" >>  $meltargs-$$-tmp
    meltbuild_arg init=$meltinit >> $meltargs-$$-tmp
    meltbuild_arg workdir=meltbuild-workdir >> $meltargs-$$-tmp
    meltbuild_arg tempdir=. >> $meltargs-$$-tmp
    meltbuild_arg source-path=$meltstage:$meltprevstage:. >> $meltargs-$$-tmp
    meltbuild_arg module-path=$meltstage:$meltprevstage:. >> $meltargs-$$-tmp
    meltbuild_arg bootstrapping  >> $meltargs-$$-tmp
    meltbuild_arg generate-work-link  >> $meltargs-$$-tmp
    meltbuild_arg generated-c-file-list=$meltstage/$meltbase.cfilist  >> $meltargs-$$-tmp
    ## final empty file
    echo meltbuild-empty-file.c >>  $meltargs-$$-tmp
    mv $meltargs-$$-tmp $meltargs
    meltbuild_info $meltfrom argument file $meltargs is
    cat  $meltargs > /dev/stderr
    $GCCMELT_CC1 @$meltargs || meltbuild_error $meltfrom failed with arguments @$meltargs
    GCCMELT_STAGE=$meltstage
}

GCCMELT_ZERO_FLAVOR=${GCCMELT_STAGE_ZERO#meltbuild-stage0-}

## The base name of the MELT translator files melt-build-script.tpl:115/3
GCCMELT_TRANSLATOR_BASE=(  warmelt-first \
  warmelt-base \
  warmelt-debug \
  warmelt-macro \
  warmelt-normal \
  warmelt-normatch \
  warmelt-genobj \
  warmelt-outobj \
  warmelt-modes )

case $GCCMELT_ZERO_FLAVOR in
    optimized) ;;
    dynamic) ;;
    debugnoline) ;;
    quicklybuilt) ;;
    *) meltbuild_error  melt-build-script.tpl:123/4 bad zero flavor $GCCMELT_ZERO_FLAVOR ;;
esac


## our stage0 melt-build-script.tpl:127/5

[ -d $GCCMELT_STAGE_ZERO ] || mkdir  $GCCMELT_STAGE_ZERO



meltbuild_info making stage0 warmelt-first  melt-build-script.tpl:133/6

##  stage0 melt-build-script.tpl:135/7 symlink descriptor file warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/8 symlink source code warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/9 symlink stamp warmelt-first
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-first+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_FIRST_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-first+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/10 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-first \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_FIRST_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-first \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/11 stage0 warmelt-first did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/12 successfully build stage0 warmelt-first


meltbuild_info making stage0 warmelt-base  melt-build-script.tpl:133/13

##  stage0 melt-build-script.tpl:135/14 symlink descriptor file warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/15 symlink source code warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/16 symlink stamp warmelt-base
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-base+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_BASE_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-base+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/17 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-base \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_BASE_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-base \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/18 stage0 warmelt-base did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/19 successfully build stage0 warmelt-base


meltbuild_info making stage0 warmelt-debug  melt-build-script.tpl:133/20

##  stage0 melt-build-script.tpl:135/21 symlink descriptor file warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/22 symlink source code warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/23 symlink stamp warmelt-debug
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-debug+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_DEBUG_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-debug+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/24 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-debug \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_DEBUG_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-debug \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/25 stage0 warmelt-debug did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/26 successfully build stage0 warmelt-debug


meltbuild_info making stage0 warmelt-macro  melt-build-script.tpl:133/27

##  stage0 melt-build-script.tpl:135/28 symlink descriptor file warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/29 symlink source code warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/30 symlink stamp warmelt-macro
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-macro+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_MACRO_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-macro+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/31 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-macro \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_MACRO_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-macro \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/32 stage0 warmelt-macro did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/33 successfully build stage0 warmelt-macro


meltbuild_info making stage0 warmelt-normal  melt-build-script.tpl:133/34

##  stage0 melt-build-script.tpl:135/35 symlink descriptor file warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/36 symlink source code warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/37 symlink stamp warmelt-normal
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normal+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_NORMAL_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-normal+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/38 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-normal \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_NORMAL_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-normal \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/39 stage0 warmelt-normal did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/40 successfully build stage0 warmelt-normal


meltbuild_info making stage0 warmelt-normatch  melt-build-script.tpl:133/41

##  stage0 melt-build-script.tpl:135/42 symlink descriptor file warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/43 symlink source code warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/44 symlink stamp warmelt-normatch
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-normatch+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_NORMATCH_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/45 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-normatch \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_NORMATCH_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-normatch \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/46 stage0 warmelt-normatch did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/47 successfully build stage0 warmelt-normatch


meltbuild_info making stage0 warmelt-genobj  melt-build-script.tpl:133/48

##  stage0 melt-build-script.tpl:135/49 symlink descriptor file warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/50 symlink source code warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/51 symlink stamp warmelt-genobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-genobj+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_GENOBJ_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/52 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-genobj \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_GENOBJ_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-genobj \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/53 stage0 warmelt-genobj did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/54 successfully build stage0 warmelt-genobj


meltbuild_info making stage0 warmelt-outobj  melt-build-script.tpl:133/55

##  stage0 melt-build-script.tpl:135/56 symlink descriptor file warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/57 symlink source code warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/58 symlink stamp warmelt-outobj
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-outobj+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/59 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-outobj \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-outobj \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/60 stage0 warmelt-outobj did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/61 successfully build stage0 warmelt-outobj


meltbuild_info making stage0 warmelt-modes  melt-build-script.tpl:133/62

##  stage0 melt-build-script.tpl:135/63 symlink descriptor file warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes+meltdesc.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+meltdesc.c $GCCMELT_STAGE_ZERO/ 
fi

##  stage0 melt-build-script.tpl:140/64 symlink source code warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes.c" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes.c $GCCMELT_STAGE_ZERO/ 
    for f in $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+[0-9]*.c ; do
	meltbuild_symlink $f $GCCMELT_STAGE_ZERO/ 
    done
fi

##  stage0 melt-build-script.tpl:148/65 symlink stamp warmelt-modes
if ! -f "$GCCMELT_STAGE_ZERO/warmelt-modes+melttime.h" ; then
    meltbuild_symlink $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+melttime.h $GCCMELT_STAGE_ZERO/ 
fi

MELT_ZERO_GENERATED_MODES_CUMULMD5=$($GAWK -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $2}' $GCCMELT_MELTSOURCEDIR/generated/warmelt-modes+meltdesc.c)

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:156/66 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=$GCCMELT_ZERO_FLAVOR \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=$GCCMELT_MELTSOURCEDIR/generated/warmelt-modes \
   GCCMELT_CUMULATED_MD5=$MELT_ZERO_GENERATED_MODES_CUMULMD5 \
   GCCMELT_MODULE_BINARYBASE=$GCCMELT_STAGE_ZERO/warmelt-modes \
   GCCMELT_MODULE_DEPENDENCIES="$GCCMELT_CC1_DEPENDENCIES" \
 || meltbuild_error  melt-build-script.tpl:164/67 stage0 warmelt-modes did not build with $GCCMELT_MAKE 

meltbuild_info melt-build-script.tpl:166/68 successfully build stage0 warmelt-modes




################################################################
################################################################
#################@ before our stages melt-build-script.tpl:173/69 



#@  begin for meltbuild-stage1 melt-build-script.tpl:177/70

[ -d meltbuild-stage1 ] || mkdir meltbuild-stage1

#### rules for meltbuild-stage1, previous $GCCMELT_STAGE_ZERO melt-build-script.tpl:186/71



### the C source of meltbuild-stage1 for warmelt-first melt-build-script.tpl:191/72
#@ melt-build-script.tpl:192/73 base warmelt-first stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/74 generating C code of warmelt-first in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/75 \
    translateinit \
    warmelt-first \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    $GCCMELT_STAGE_ZERO/warmelt-first.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-base.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-debug.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-macro.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normal.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/76 compiling module warmelt-first in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/77 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-first \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-first \
 || meltbuild_error  melt-build-script.tpl:219/78 stage meltbuild-stage1 failed to make module warmelt-first

#@ melt-build-script.tpl:221/79 end base warmelt-first stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-base melt-build-script.tpl:191/80
#@ melt-build-script.tpl:192/81 base warmelt-base stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/82 generating C code of warmelt-base in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/83 \
    translatefile \
    warmelt-base \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-base.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-debug.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-macro.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normal.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/84 compiling module warmelt-base in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/85 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-base \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-base \
 || meltbuild_error  melt-build-script.tpl:219/86 stage meltbuild-stage1 failed to make module warmelt-base

#@ melt-build-script.tpl:221/87 end base warmelt-base stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-debug melt-build-script.tpl:191/88
#@ melt-build-script.tpl:192/89 base warmelt-debug stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/90 generating C code of warmelt-debug in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/91 \
    translatefile \
    warmelt-debug \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-debug.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-macro.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normal.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/92 compiling module warmelt-debug in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/93 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-debug \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-debug \
 || meltbuild_error  melt-build-script.tpl:219/94 stage meltbuild-stage1 failed to make module warmelt-debug

#@ melt-build-script.tpl:221/95 end base warmelt-debug stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-macro melt-build-script.tpl:191/96
#@ melt-build-script.tpl:192/97 base warmelt-macro stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/98 generating C code of warmelt-macro in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/99 \
    translatefile \
    warmelt-macro \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-macro.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normal.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/100 compiling module warmelt-macro in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/101 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-macro \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-macro \
 || meltbuild_error  melt-build-script.tpl:219/102 stage meltbuild-stage1 failed to make module warmelt-macro

#@ melt-build-script.tpl:221/103 end base warmelt-macro stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-normal melt-build-script.tpl:191/104
#@ melt-build-script.tpl:192/105 base warmelt-normal stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/106 generating C code of warmelt-normal in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/107 \
    translatefile \
    warmelt-normal \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-normal.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    "warmelt-predef.melt"


meltbuild_info melt-build-script.tpl:210/108 compiling module warmelt-normal in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/109 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-normal \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-normal \
 || meltbuild_error  melt-build-script.tpl:219/110 stage meltbuild-stage1 failed to make module warmelt-normal

#@ melt-build-script.tpl:221/111 end base warmelt-normal stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-normatch melt-build-script.tpl:191/112
#@ melt-build-script.tpl:192/113 base warmelt-normatch stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/114 generating C code of warmelt-normatch in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/115 \
    translatefile \
    warmelt-normatch \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-normatch.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/116 compiling module warmelt-normatch in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/117 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-normatch \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-normatch \
 || meltbuild_error  melt-build-script.tpl:219/118 stage meltbuild-stage1 failed to make module warmelt-normatch

#@ melt-build-script.tpl:221/119 end base warmelt-normatch stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-genobj melt-build-script.tpl:191/120
#@ melt-build-script.tpl:192/121 base warmelt-genobj stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/122 generating C code of warmelt-genobj in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/123 \
    translatefile \
    warmelt-genobj \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-genobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/124 compiling module warmelt-genobj in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/125 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-genobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-genobj \
 || meltbuild_error  melt-build-script.tpl:219/126 stage meltbuild-stage1 failed to make module warmelt-genobj

#@ melt-build-script.tpl:221/127 end base warmelt-genobj stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-outobj melt-build-script.tpl:191/128
#@ melt-build-script.tpl:192/129 base warmelt-outobj stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/130 generating C code of warmelt-outobj in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/131 \
    translatefile \
    warmelt-outobj \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-outobj.$GCCMELT_ZERO_FLAVOR:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/132 compiling module warmelt-outobj in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/133 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-outobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-outobj \
 || meltbuild_error  melt-build-script.tpl:219/134 stage meltbuild-stage1 failed to make module warmelt-outobj

#@ melt-build-script.tpl:221/135 end base warmelt-outobj stage meltbuild-stage1 


### the C source of meltbuild-stage1 for warmelt-modes melt-build-script.tpl:191/136
#@ melt-build-script.tpl:192/137 base warmelt-modes stage meltbuild-stage1 prevstage $GCCMELT_STAGE_ZERO prevflavor  $GCCMELT_ZERO_FLAVOR 

meltbuild_info melt-build-script.tpl:194/138 generating C code of warmelt-modes in meltbuild-stage1

meltbuild_emit melt-build-script.tpl:196/139 \
    translatefile \
    warmelt-modes \
    "meltbuild-stage1" \
    "$GCCMELT_STAGE_ZERO" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:$GCCMELT_STAGE_ZERO/warmelt-modes.$GCCMELT_ZERO_FLAVOR \
    ""


meltbuild_info melt-build-script.tpl:210/140 compiling module warmelt-modes in meltbuild-stage1

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/141 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage1/warmelt-modes \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage1/warmelt-modes \
 || meltbuild_error  melt-build-script.tpl:219/142 stage meltbuild-stage1 failed to make module warmelt-modes

#@ melt-build-script.tpl:221/143 end base warmelt-modes stage meltbuild-stage1 



########@  end for meltbuild-stage1 melt-build-script.tpl:225/144

#@  begin for meltbuild-stage2 melt-build-script.tpl:177/145

[ -d meltbuild-stage2 ] || mkdir meltbuild-stage2

#### rules for meltbuild-stage2, previous meltbuild-stage1 melt-build-script.tpl:186/146



### the C source of meltbuild-stage2 for warmelt-first melt-build-script.tpl:191/147
#@ melt-build-script.tpl:192/148 base warmelt-first stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/149 generating C code of warmelt-first in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/150 \
    translateinit \
    warmelt-first \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage1/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/151 compiling module warmelt-first in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/152 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-first \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-first \
 || meltbuild_error  melt-build-script.tpl:219/153 stage meltbuild-stage2 failed to make module warmelt-first

#@ melt-build-script.tpl:221/154 end base warmelt-first stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-base melt-build-script.tpl:191/155
#@ melt-build-script.tpl:192/156 base warmelt-base stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/157 generating C code of warmelt-base in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/158 \
    translatefile \
    warmelt-base \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage1/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/159 compiling module warmelt-base in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/160 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-base \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-base \
 || meltbuild_error  melt-build-script.tpl:219/161 stage meltbuild-stage2 failed to make module warmelt-base

#@ melt-build-script.tpl:221/162 end base warmelt-base stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-debug melt-build-script.tpl:191/163
#@ melt-build-script.tpl:192/164 base warmelt-debug stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/165 generating C code of warmelt-debug in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/166 \
    translatefile \
    warmelt-debug \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage1/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/167 compiling module warmelt-debug in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/168 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-debug \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-debug \
 || meltbuild_error  melt-build-script.tpl:219/169 stage meltbuild-stage2 failed to make module warmelt-debug

#@ melt-build-script.tpl:221/170 end base warmelt-debug stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-macro melt-build-script.tpl:191/171
#@ melt-build-script.tpl:192/172 base warmelt-macro stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/173 generating C code of warmelt-macro in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/174 \
    translatefile \
    warmelt-macro \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage1/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/175 compiling module warmelt-macro in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/176 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-macro \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-macro \
 || meltbuild_error  melt-build-script.tpl:219/177 stage meltbuild-stage2 failed to make module warmelt-macro

#@ melt-build-script.tpl:221/178 end base warmelt-macro stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-normal melt-build-script.tpl:191/179
#@ melt-build-script.tpl:192/180 base warmelt-normal stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/181 generating C code of warmelt-normal in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/182 \
    translatefile \
    warmelt-normal \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage1/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    "warmelt-predef.melt"


meltbuild_info melt-build-script.tpl:210/183 compiling module warmelt-normal in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/184 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-normal \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-normal \
 || meltbuild_error  melt-build-script.tpl:219/185 stage meltbuild-stage2 failed to make module warmelt-normal

#@ melt-build-script.tpl:221/186 end base warmelt-normal stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-normatch melt-build-script.tpl:191/187
#@ melt-build-script.tpl:192/188 base warmelt-normatch stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/189 generating C code of warmelt-normatch in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/190 \
    translatefile \
    warmelt-normatch \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage1/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/191 compiling module warmelt-normatch in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/192 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-normatch \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-normatch \
 || meltbuild_error  melt-build-script.tpl:219/193 stage meltbuild-stage2 failed to make module warmelt-normatch

#@ melt-build-script.tpl:221/194 end base warmelt-normatch stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-genobj melt-build-script.tpl:191/195
#@ melt-build-script.tpl:192/196 base warmelt-genobj stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/197 generating C code of warmelt-genobj in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/198 \
    translatefile \
    warmelt-genobj \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage1/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/199 compiling module warmelt-genobj in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/200 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-genobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-genobj \
 || meltbuild_error  melt-build-script.tpl:219/201 stage meltbuild-stage2 failed to make module warmelt-genobj

#@ melt-build-script.tpl:221/202 end base warmelt-genobj stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-outobj melt-build-script.tpl:191/203
#@ melt-build-script.tpl:192/204 base warmelt-outobj stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/205 generating C code of warmelt-outobj in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/206 \
    translatefile \
    warmelt-outobj \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage1/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/207 compiling module warmelt-outobj in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/208 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-outobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-outobj \
 || meltbuild_error  melt-build-script.tpl:219/209 stage meltbuild-stage2 failed to make module warmelt-outobj

#@ melt-build-script.tpl:221/210 end base warmelt-outobj stage meltbuild-stage2 


### the C source of meltbuild-stage2 for warmelt-modes melt-build-script.tpl:191/211
#@ melt-build-script.tpl:192/212 base warmelt-modes stage meltbuild-stage2 prevstage meltbuild-stage1 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/213 generating C code of warmelt-modes in meltbuild-stage2

meltbuild_emit melt-build-script.tpl:196/214 \
    translatefile \
    warmelt-modes \
    "meltbuild-stage2" \
    "meltbuild-stage1" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage1/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/215 compiling module warmelt-modes in meltbuild-stage2

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/216 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage2/warmelt-modes \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage2/warmelt-modes \
 || meltbuild_error  melt-build-script.tpl:219/217 stage meltbuild-stage2 failed to make module warmelt-modes

#@ melt-build-script.tpl:221/218 end base warmelt-modes stage meltbuild-stage2 



########@  end for meltbuild-stage2 melt-build-script.tpl:225/219

#@  begin for meltbuild-stage3 melt-build-script.tpl:177/220

[ -d meltbuild-stage3 ] || mkdir meltbuild-stage3

#### rules for meltbuild-stage3, previous meltbuild-stage2 melt-build-script.tpl:186/221



### the C source of meltbuild-stage3 for warmelt-first melt-build-script.tpl:191/222
#@ melt-build-script.tpl:192/223 base warmelt-first stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/224 generating C code of warmelt-first in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/225 \
    translateinit \
    warmelt-first \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage2/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/226 compiling module warmelt-first in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/227 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-first \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-first \
 || meltbuild_error  melt-build-script.tpl:219/228 stage meltbuild-stage3 failed to make module warmelt-first

#@ melt-build-script.tpl:221/229 end base warmelt-first stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-base melt-build-script.tpl:191/230
#@ melt-build-script.tpl:192/231 base warmelt-base stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/232 generating C code of warmelt-base in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/233 \
    translatefile \
    warmelt-base \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage2/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/234 compiling module warmelt-base in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/235 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-base \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-base \
 || meltbuild_error  melt-build-script.tpl:219/236 stage meltbuild-stage3 failed to make module warmelt-base

#@ melt-build-script.tpl:221/237 end base warmelt-base stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-debug melt-build-script.tpl:191/238
#@ melt-build-script.tpl:192/239 base warmelt-debug stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/240 generating C code of warmelt-debug in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/241 \
    translatefile \
    warmelt-debug \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage2/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/242 compiling module warmelt-debug in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/243 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-debug \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-debug \
 || meltbuild_error  melt-build-script.tpl:219/244 stage meltbuild-stage3 failed to make module warmelt-debug

#@ melt-build-script.tpl:221/245 end base warmelt-debug stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-macro melt-build-script.tpl:191/246
#@ melt-build-script.tpl:192/247 base warmelt-macro stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/248 generating C code of warmelt-macro in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/249 \
    translatefile \
    warmelt-macro \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage2/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/250 compiling module warmelt-macro in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/251 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-macro \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-macro \
 || meltbuild_error  melt-build-script.tpl:219/252 stage meltbuild-stage3 failed to make module warmelt-macro

#@ melt-build-script.tpl:221/253 end base warmelt-macro stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-normal melt-build-script.tpl:191/254
#@ melt-build-script.tpl:192/255 base warmelt-normal stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/256 generating C code of warmelt-normal in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/257 \
    translatefile \
    warmelt-normal \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage3/warmelt-macro.quicklybuilt:meltbuild-stage2/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    "warmelt-predef.melt"


meltbuild_info melt-build-script.tpl:210/258 compiling module warmelt-normal in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/259 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-normal \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-normal \
 || meltbuild_error  melt-build-script.tpl:219/260 stage meltbuild-stage3 failed to make module warmelt-normal

#@ melt-build-script.tpl:221/261 end base warmelt-normal stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-normatch melt-build-script.tpl:191/262
#@ melt-build-script.tpl:192/263 base warmelt-normatch stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/264 generating C code of warmelt-normatch in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/265 \
    translatefile \
    warmelt-normatch \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage3/warmelt-macro.quicklybuilt:meltbuild-stage3/warmelt-normal.quicklybuilt:meltbuild-stage2/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/266 compiling module warmelt-normatch in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/267 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-normatch \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-normatch \
 || meltbuild_error  melt-build-script.tpl:219/268 stage meltbuild-stage3 failed to make module warmelt-normatch

#@ melt-build-script.tpl:221/269 end base warmelt-normatch stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-genobj melt-build-script.tpl:191/270
#@ melt-build-script.tpl:192/271 base warmelt-genobj stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/272 generating C code of warmelt-genobj in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/273 \
    translatefile \
    warmelt-genobj \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage3/warmelt-macro.quicklybuilt:meltbuild-stage3/warmelt-normal.quicklybuilt:meltbuild-stage3/warmelt-normatch.quicklybuilt:meltbuild-stage2/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/274 compiling module warmelt-genobj in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/275 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-genobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-genobj \
 || meltbuild_error  melt-build-script.tpl:219/276 stage meltbuild-stage3 failed to make module warmelt-genobj

#@ melt-build-script.tpl:221/277 end base warmelt-genobj stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-outobj melt-build-script.tpl:191/278
#@ melt-build-script.tpl:192/279 base warmelt-outobj stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/280 generating C code of warmelt-outobj in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/281 \
    translatefile \
    warmelt-outobj \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage3/warmelt-macro.quicklybuilt:meltbuild-stage3/warmelt-normal.quicklybuilt:meltbuild-stage3/warmelt-normatch.quicklybuilt:meltbuild-stage3/warmelt-genobj.quicklybuilt:meltbuild-stage2/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/282 compiling module warmelt-outobj in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/283 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-outobj \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-outobj \
 || meltbuild_error  melt-build-script.tpl:219/284 stage meltbuild-stage3 failed to make module warmelt-outobj

#@ melt-build-script.tpl:221/285 end base warmelt-outobj stage meltbuild-stage3 


### the C source of meltbuild-stage3 for warmelt-modes melt-build-script.tpl:191/286
#@ melt-build-script.tpl:192/287 base warmelt-modes stage meltbuild-stage3 prevstage meltbuild-stage2 prevflavor  quicklybuilt 

meltbuild_info melt-build-script.tpl:194/288 generating C code of warmelt-modes in meltbuild-stage3

meltbuild_emit melt-build-script.tpl:196/289 \
    translatefile \
    warmelt-modes \
    "meltbuild-stage3" \
    "meltbuild-stage2" \
    meltbuild-stage3/warmelt-first.quicklybuilt:meltbuild-stage3/warmelt-base.quicklybuilt:meltbuild-stage3/warmelt-debug.quicklybuilt:meltbuild-stage3/warmelt-macro.quicklybuilt:meltbuild-stage3/warmelt-normal.quicklybuilt:meltbuild-stage3/warmelt-normatch.quicklybuilt:meltbuild-stage3/warmelt-genobj.quicklybuilt:meltbuild-stage3/warmelt-outobj.quicklybuilt:meltbuild-stage2/warmelt-modes.quicklybuilt \
    ""


meltbuild_info melt-build-script.tpl:210/290 compiling module warmelt-modes in meltbuild-stage3

$GCCMELT_MAKE -f $GCCMELT_MODULE_MK melt_module \
   GCCMELT_FROM=melt-build-script.tpl:213/291 \
   GCCMELT_MODULE_WORKSPACE=meltbuild-workdir \
   GCCMELT_MODULE_FLAVOR=quicklybuilt \
   GCCMELT_CFLAGS="$GCCMELT_COMPILER_FLAGS" \
   GCCMELT_MODULE_SOURCEBASE=meltbuild-stage3/warmelt-modes \
   GCCMELT_MODULE_BINARYBASE=meltbuild-stage3/warmelt-modes \
 || meltbuild_error  melt-build-script.tpl:219/292 stage meltbuild-stage3 failed to make module warmelt-modes

#@ melt-build-script.tpl:221/293 end base warmelt-modes stage meltbuild-stage3 



########@  end for meltbuild-stage3 melt-build-script.tpl:225/294



################
meltbuild_info melt-build-script.tpl:230/295 successfully done
#@ eof melt-build-script.tpl:231/296 end of generated melt-build-script.sh
