
#@!  -*- buffer-read-only: t -*- vi: set ro:
#@#@# 
#@#@# DO NOT EDIT THIS FILE   (melt-newbuild.mk)
#@#@# 
#@#@# It has been AutoGen-ed  June 27, 2012 at 11:26:24 AM by AutoGen 5.16
#@#@# From the definitions    melt-newbuild.def
#@#@# and the template file   melt-newbuild.tpl
##@@ melt-newbuild.mk is generated from melt-newbuild.tpl by 'autogen melt-newbuild.def'
#
# Makefile fragment for MELT modules and MELT translator bootstrap.
#   Copyright (C) 2010,2011,2012  Free Software Foundation
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
#@ from melt-newbuild.tpl line 22 generated by Autogen 5.16 using melt-newbuild.def
## See http://stackoverflow.com/q/8727896/841108
## and http://lists.gnu.org/archive/html/help-make/2012-01/msg00017.html
## and http://gcc.gnu.org/ml/gcc/2012-01/msg00089.html
## and Ian Taylor's explanation http://gcc.gnu.org/ml/gcc/2012-01/msg00090.html
## Using remake http://bashdb.sourceforge.net/remake/ may help debugging this.
## Conventionally, all our timestamp files lie in the current directory.

#@ default MELT variant from melt-newbuild.tpl line 30
melt_default_variant ?= optimized

## the following Makefile variables are expected to be set from melt-newbuild.tpl line 33 


#@ from melt-newbuild.tpl line 62 name= melt_source_dir comment=   directory containing *.melt & *.c files
ifndef melt_source_dir
$(warning unknown melt_source_dir :::  directory containing *.melt & *.c files)
endif



#@ from melt-newbuild.tpl line 62 name= melt_module_dir comment=   directory containing *.so MELT module files
ifndef melt_module_dir
$(warning unknown melt_module_dir :::  directory containing *.so MELT module files)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_module_makefile comment=   our melt-module.mk Makefile  when making MELT
ifndef melt_make_module_makefile
$(warning unknown melt_make_module_makefile :::  our melt-module.mk Makefile  when making MELT)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_source_dir comment=   directory containing the *.melt files when making MELT
ifndef melt_make_source_dir
$(warning unknown melt_make_source_dir :::  directory containing the *.melt files when making MELT)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_module_dir comment=   directory containing the *.so files when making MELT
ifndef melt_make_module_dir
$(warning unknown melt_make_module_dir :::  directory containing the *.so files when making MELT)
endif



#@ from melt-newbuild.tpl line 62 name= melt_default_modules_list comment=   basename of the default module list
ifndef melt_default_modules_list
$(warning unknown melt_default_modules_list :::  basename of the default module list)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_cc1 comment=   gcc -fplugin=melt or cc1-melt program within MELT branch
ifndef melt_make_cc1
$(warning unknown melt_make_cc1 :::  gcc -fplugin=melt or cc1-melt program within MELT branch)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_cc1_dependency comment=   the make dependency for above
ifndef melt_make_cc1_dependency
$(warning unknown melt_make_cc1_dependency :::  the make dependency for above)
endif



#@ from melt-newbuild.tpl line 62 name= melt_make_gencdeps comment=   extra make dependency of generated C files -often empty-
ifndef melt_make_gencdeps
$(warning unknown melt_make_gencdeps :::  extra make dependency of generated C files -often empty-)
endif



#@ from melt-newbuild.tpl line 62 name= melt_move_if_change comment=   a move if change command for MELT
ifndef melt_move_if_change
$(warning unknown melt_move_if_change :::  a move if change command for MELT)
endif



#@ from melt-newbuild.tpl line 62 name= melt_cflags comment=   the CFLAGS for compiling MELT generated C code
ifndef melt_cflags
$(warning unknown melt_cflags :::  the CFLAGS for compiling MELT generated C code)
endif



#@ from melt-newbuild.tpl line 62 name= melt_xtra_cflags comment=   th CFLAGS for compiling extra applicative C code - often empty
ifndef melt_xtra_cflags
$(warning unknown melt_xtra_cflags :::  th CFLAGS for compiling extra applicative C code - often empty)
endif



#@ from melt-newbuild.tpl line 62 name= melt_default_variant comment=   quicklybuilt | optimized | debugnoline
ifndef melt_default_variant
$(warning unknown melt_default_variant :::  quicklybuilt | optimized | debugnoline)
endif





## LN_S might not be defined, e.g. in MELT-Plugin-Makefile from melt-newbuild.tpl line 71
LN_S ?= ln -sv

## GAWK is needed, the GNU awk from melt-newbuild.tpl line 74
GAWK ?= gawk

## the md5sum utility is needed  from melt-newbuild.tpl line 77
MD5SUM ?= md5sum

## the various arguments to MELT - avoid spaces in them! from melt-newbuild.tpl line 80
meltarg_mode=$(if $(melt_is_plugin),-fplugin-arg-melt-mode,-fmelt-mode)
meltarg_init=$(if $(melt_is_plugin),-fplugin-arg-melt-init,-fmelt-init)
meltarg_module_path=$(if $(melt_is_plugin),-fplugin-arg-melt-module-path,-fmelt-module-path)
meltarg_source_path=$(if $(melt_is_plugin),-fplugin-arg-melt-source-path,-fmelt-source-path)
meltarg_tempdir=$(if $(melt_is_plugin),-fplugin-arg-melt-tempdir,-fmelt-tempdir)
meltarg_workdir=$(if $(melt_is_plugin),-fplugin-arg-melt-workdir,-fmelt-workdir)
meltarg_arg=$(if $(melt_is_plugin),-fplugin-arg-melt-arg,-fmelt-arg)
meltarg_bootstrapping=$(if $(melt_is_plugin),-fplugin-arg-melt-bootstrapping,-fmelt-bootstrapping)
meltarg_genworklink=$(if $(melt_is_plugin),-fplugin-arg-melt-generate-work-link,-fmelt-generate-work-link)
meltarg_makefile=$(if $(melt_is_plugin),-fplugin-arg-melt-module-makefile,-fmelt-module-makefile)
meltarg_makecmd=$(if $(melt_is_plugin),-fplugin-arg-melt-module-make-command,-fmelt-module-make-command)
meltarg_arglist=$(if $(melt_is_plugin),-fplugin-arg-melt-arglist,-fmelt-arglist)
meltarg_output=$(if $(melt_is_plugin),-fplugin-arg-melt-output,-fmelt-output)
meltarg_modulecflags=$(if $(melt_is_plugin),-fplugin-arg-melt-module-cflags,-fmelt-module-cflags)
meltarg_inhibitautobuild=$(if $(melt_is_plugin),-fplugin-arg-melt-inhibit-auto-build,-fmelt-inhibit-auto-build)

## compiler used to compile MELT generated C (or C++ compatible) code  from melt-newbuild.tpl line 97
ifndef GCCMELT_COMPILER
$(error GCCMELT_COMPILER should be explicitly given  from melt-newbuild.tpl line 99)
endif

## compiler flags from melt-newbuild.tpl line 102
ifndef GCCMELT_COMPILER_FLAGS
$(error GCCMELT_COMPILER_FLAGS should be explicitly given  from melt-newbuild.tpl line 104)
endif

## linker used to link the shared object modules from melt-newbuild.tpl line 107
ifndef GCCMELT_LINKER
$(error GCCMELT_LINKER should be explicitly given  from melt-newbuild.tpl line 109)
endif

## linker flags from melt-newbuild.tpl line 112
ifndef GCCMELT_LINKER_FLAGS
$(error GCCMELT_LINKER_FLAGS should be explicitly given  from melt-newbuild.tpl line 114)
endif

## position independent flag to compile *.c into *pic.o from melt-newbuild.tpl line 117
GCCMELT_PIC_FLAGS ?= -fPIC

## shared object flag to link *pic.o into *.so from melt-newbuild.tpl line 120
GCCMELT_SHARED_FLAGS ?= -shared

## extract important flags from melt-build.mk  from melt-newbuild.tpl line 123
melt-module-frag.mk: $(melt_make_module_makefile)
	sed -n -e '/##__BEGINFRAGMELT/,/##__ENDFRAGMELT/p' $< > $@-tmp
	mv $@-tmp $@

include melt-module-frag.mk

 

##xflavor descriptor from melt-newbuild.tpl line 132
GCCMELT_COMPILER_DESCRIPTOR_FLAGS= $(GCCMELT_DESCRIPTOR_FLAGS) $(GCCMELT_DESCRIPTOR_PREPROFLAGS)
GCCMELT_LINKER_DESCRIPTOR_FLAGS= $(GCCMELT_DESCRIPTOR_FLAGS)

 

##xflavor dynamic from melt-newbuild.tpl line 132
GCCMELT_COMPILER_DYNAMIC_FLAGS= $(GCCMELT_DYNAMIC_FLAGS) $(GCCMELT_DYNAMIC_PREPROFLAGS)
GCCMELT_LINKER_DYNAMIC_FLAGS= $(GCCMELT_DYNAMIC_FLAGS)

 

##xflavor quicklybuilt from melt-newbuild.tpl line 132
GCCMELT_COMPILER_QUICKLYBUILT_FLAGS= $(GCCMELT_QUICKLYBUILT_FLAGS) $(GCCMELT_QUICKLYBUILT_PREPROFLAGS)
GCCMELT_LINKER_QUICKLYBUILT_FLAGS= $(GCCMELT_QUICKLYBUILT_FLAGS)

 

##xflavor optimized from melt-newbuild.tpl line 132
GCCMELT_COMPILER_OPTIMIZED_FLAGS= $(GCCMELT_OPTIMIZED_FLAGS) $(GCCMELT_OPTIMIZED_PREPROFLAGS)
GCCMELT_LINKER_OPTIMIZED_FLAGS= $(GCCMELT_OPTIMIZED_FLAGS)

 

##xflavor debugnoline from melt-newbuild.tpl line 132
GCCMELT_COMPILER_DEBUGNOLINE_FLAGS= $(GCCMELT_DEBUGNOLINE_FLAGS) $(GCCMELT_DEBUGNOLINE_PREPROFLAGS)
GCCMELT_LINKER_DEBUGNOLINE_FLAGS= $(GCCMELT_DEBUGNOLINE_FLAGS)



##############################################  from melt-newbuild.tpl line 138
## The base name of the MELT translator files from melt-newbuild.tpl line 139
MELT_TRANSLATOR_BASE= \
    warmelt-first \
  warmelt-base \
  warmelt-debug \
  warmelt-macro \
  warmelt-normal \
  warmelt-normatch \
  warmelt-genobj \
  warmelt-outobj \
  warmelt-modes

## the MELT translator MELT source files from melt-newbuild.tpl line 143
MELT_TRANSLATOR_SOURCE= $(patsubst %,$(melt_make_source_dir)/%.melt,$(MELT_TRANSLATOR_BASE))

## The base name of the MELT application files from melt-newbuild.tpl line 146
MELT_APPLICATION_BASE= \
    xtramelt-ana-base \
  xtramelt-ana-tree \
  xtramelt-ana-gimple \
  xtramelt-probe \
  xtramelt-ana-simple \
  xtramelt-c-generator \
  xtramelt-opengpu

## The MELT application source files from melt-newbuild.tpl line 150
MELT_APPLICATION_SOURCE= $(patsubst %,$(melt_make_source_dir)/%.melt,$(MELT_APPLICATION_BASE))

## The cold stage 0 of the translator from melt-newbuild.tpl line 153

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_FIRST_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-first.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-first+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_FIRST_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_FIRST_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_FIRST_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_FIRST_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-first+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_BASE_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-base.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-base+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_BASE_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_BASE_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_BASE_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_BASE_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-base+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_DEBUG_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-debug.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-debug+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_DEBUG_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_DEBUG_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_DEBUG_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_DEBUG_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-debug+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_MACRO_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-macro.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-macro+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_MACRO_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_MACRO_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_MACRO_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_MACRO_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-macro+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_NORMAL_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-normal.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-normal+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_NORMAL_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_NORMAL_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_NORMAL_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_NORMAL_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-normal+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_NORMATCH_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-normatch.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-normatch+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_NORMATCH_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_NORMATCH_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_NORMATCH_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_NORMATCH_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-normatch+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_GENOBJ_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-genobj.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-genobj+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_GENOBJ_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_GENOBJ_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_GENOBJ_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_GENOBJ_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-genobj+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_OUTOBJ_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-outobj.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-outobj+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_OUTOBJ_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_OUTOBJ_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_OUTOBJ_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-outobj+meltdesc.c)

#@ The C files of the stage 0 are deposited from melt-newbuild.tpl line 155
MELT_ZERO_GENERATED_MODES_C_FILES= \
                  $(realpath $(melt_make_source_dir))/generated/warmelt-modes.c \
                  $(wildcard $(realpath $(melt_make_source_dir))/generated/warmelt-modes+*.c)
# The base names of stage 0 files from melt-newbuild.tpl line 159
MELT_ZERO_GENERATED_MODES_BASE= \
                  $(basename $(notdir $(MELT_GENERATED_MODES_C_FILES)))
# for stage 0 files, we don't compute the checksum, we extract what was deposited from melt-newbuild.tpl line 162
## avoid spaces in MELT_GENERATED_MODES_CUMULMD5 below from melt-newbuild.tpl line 163
MELT_ZERO_GENERATED_MODES_CUMULMD5:=$(shell $(GAWK) -F\" '/extern/{next} /melt_cumulated_hexmd5/{print $$2}' $(melt_make_source_dir)/generated/warmelt-modes+meltdesc.c)


## An empty file is needed for every MELT translation from melt-newbuild.tpl line 167
empty-file-for-melt.c:
	date +"/* empty-file-for-melt.c %c */" > $@-tmp
	mv $@-tmp $@

.PHONY: warmelt0

## the default stage0 is from melt-newbuild.tpl line 174
MELT_STAGE_ZERO?=melt-stage0-dynamic
MELT_ZERO_FLAVOR=$(patsubst melt-stage0-%,%,$(MELT_STAGE_ZERO))

warmelt0: $(MELT_STAGE_ZERO)/$(MELT_STAGE_ZERO).stamp


## stage 0 flavor dynamic  from melt-newbuild.tpl line 181

melt-stage0-dynamic:
	test -d  melt-stage0-dynamic/ || mkdir  melt-stage0-dynamic/

#@  from melt-newbuild.tpl line 186
melt-stage0-dynamic/melt-stage0-dynamic.stamp: \
  melt-stage0-dynamic/warmelt-first.$(MELT_ZERO_GENERATED_FIRST_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-base.$(MELT_ZERO_GENERATED_BASE_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-debug.$(MELT_ZERO_GENERATED_DEBUG_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-macro.$(MELT_ZERO_GENERATED_MACRO_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-normal.$(MELT_ZERO_GENERATED_NORMAL_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-normatch.$(MELT_ZERO_GENERATED_NORMATCH_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-genobj.$(MELT_ZERO_GENERATED_GENOBJ_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-outobj.$(MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5).dynamic.meltmod.so \
  melt-stage0-dynamic/warmelt-modes.$(MELT_ZERO_GENERATED_MODES_CUMULMD5).dynamic.meltmod.so \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_FIRST_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_BASE_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_DEBUG_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_MACRO_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_NORMAL_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_NORMATCH_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_GENOBJ_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_OUTOBJ_C_FILES))) \
  $(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_MODES_C_FILES))) |  melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic. at= $@ left= $< circ= $^ from melt-newbuild.tpl line 192
	$(MD5SUM) $^ > $@-tmp
	$(melt_move_if_change) $@-tmp $@


#@ from melt-newbuild.tpl line 197 symbolic links for stage 0 sources dynamic

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_FIRST_C_FILES))  warmelt-first+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-first.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_BASE_C_FILES))  warmelt-base+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-base.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_DEBUG_C_FILES))  warmelt-debug+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-debug.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_MACRO_C_FILES))  warmelt-macro+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-macro.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_NORMAL_C_FILES))  warmelt-normal+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normal.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_NORMATCH_C_FILES))  warmelt-normatch+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normatch.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_GENOBJ_C_FILES))  warmelt-genobj+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-genobj.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_OUTOBJ_C_FILES))  warmelt-outobj+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-outobj.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-dynamic/,$(notdir $(MELT_ZERO_GENERATED_MODES_C_FILES))  warmelt-modes+melttime.h): | melt-stage0-dynamic
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-modes.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-dynamic/
#@ from melt-newbuild.tpl line 202


#@ from melt-newbuild.tpl line 205 module and object files for stage 0 dynamic



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-first.$(MELT_ZERO_GENERATED_FIRST_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-first+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_FIRST_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-first.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-first+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-first+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-first.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-first%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-first%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-first.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-base.$(MELT_ZERO_GENERATED_BASE_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-base+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_BASE_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-base.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-base+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-base+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-base.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-base%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-base%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-base.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-debug.$(MELT_ZERO_GENERATED_DEBUG_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-debug+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_DEBUG_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-debug.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-debug+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-debug+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-debug.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-debug%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-debug%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-debug.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-macro.$(MELT_ZERO_GENERATED_MACRO_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-macro+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_MACRO_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-macro.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-macro+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-macro+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-macro.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-macro%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-macro%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-macro.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-normal.$(MELT_ZERO_GENERATED_NORMAL_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-normal+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_NORMAL_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normal.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-normal+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-normal+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-normal.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-normal%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-normal%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normal.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-normatch.$(MELT_ZERO_GENERATED_NORMATCH_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-normatch+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_NORMATCH_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normatch.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-normatch+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-normatch+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-normatch.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-normatch%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-normatch%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-normatch.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-genobj.$(MELT_ZERO_GENERATED_GENOBJ_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-genobj+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_GENOBJ_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-genobj.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-genobj+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-genobj+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-genobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-genobj%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-genobj%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-genobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-outobj.$(MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-outobj+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_OUTOBJ_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-outobj.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-outobj+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-outobj+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-outobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-outobj%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-outobj%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-outobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-dynamic/warmelt-modes.$(MELT_ZERO_GENERATED_MODES_CUMULMD5).dynamic.meltmod.so: \
  melt-stage0-dynamic/warmelt-modes+meltdesc.zpic.o $(addprefix melt-stage0-dynamic/,$(addsuffix .dynamic.zpic.o,$(MELT_ZERO_GENERATED_MODES_BASE)))
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-modes.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_DYNAMIC_FLAGS) -o $@ $^

melt-stage0-dynamic/warmelt-modes+meltdesc.zpic.o: melt-stage0-dynamic/warmelt-modes+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-modes.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-dynamic/warmelt-modes%.dynamic.zpic.o: melt-stage0-dynamic/warmelt-modes%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-dynamic.warmelt-modes.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DYNAMIC_FLAGS) -c -o $@ $<



## end stage 0 flavor dynamic  from melt-newbuild.tpl line 225

## stage 0 flavor quicklybuilt  from melt-newbuild.tpl line 181

melt-stage0-quicklybuilt:
	test -d  melt-stage0-quicklybuilt/ || mkdir  melt-stage0-quicklybuilt/

#@  from melt-newbuild.tpl line 186
melt-stage0-quicklybuilt/melt-stage0-quicklybuilt.stamp: \
  melt-stage0-quicklybuilt/warmelt-first.$(MELT_ZERO_GENERATED_FIRST_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-base.$(MELT_ZERO_GENERATED_BASE_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-debug.$(MELT_ZERO_GENERATED_DEBUG_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-macro.$(MELT_ZERO_GENERATED_MACRO_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-normal.$(MELT_ZERO_GENERATED_NORMAL_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-normatch.$(MELT_ZERO_GENERATED_NORMATCH_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-genobj.$(MELT_ZERO_GENERATED_GENOBJ_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-outobj.$(MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5).quicklybuilt.meltmod.so \
  melt-stage0-quicklybuilt/warmelt-modes.$(MELT_ZERO_GENERATED_MODES_CUMULMD5).quicklybuilt.meltmod.so \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_FIRST_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_BASE_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_DEBUG_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_MACRO_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_NORMAL_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_NORMATCH_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_GENOBJ_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_OUTOBJ_C_FILES))) \
  $(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_MODES_C_FILES))) |  melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt. at= $@ left= $< circ= $^ from melt-newbuild.tpl line 192
	$(MD5SUM) $^ > $@-tmp
	$(melt_move_if_change) $@-tmp $@


#@ from melt-newbuild.tpl line 197 symbolic links for stage 0 sources quicklybuilt

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_FIRST_C_FILES))  warmelt-first+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-first.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_BASE_C_FILES))  warmelt-base+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-base.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_DEBUG_C_FILES))  warmelt-debug+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-debug.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_MACRO_C_FILES))  warmelt-macro+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-macro.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_NORMAL_C_FILES))  warmelt-normal+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normal.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_NORMATCH_C_FILES))  warmelt-normatch+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normatch.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_GENOBJ_C_FILES))  warmelt-genobj+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-genobj.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_OUTOBJ_C_FILES))  warmelt-outobj+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-outobj.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202

$(addprefix melt-stage0-quicklybuilt/,$(notdir $(MELT_ZERO_GENERATED_MODES_C_FILES))  warmelt-modes+melttime.h): | melt-stage0-quicklybuilt
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-modes.srcsymlink at= $@ left= $< circ= $^ from melt-newbuild.tpl line 200
	$(LN_S) $(realpath $(melt_make_source_dir)/generated/$(@F)) melt-stage0-quicklybuilt/
#@ from melt-newbuild.tpl line 202


#@ from melt-newbuild.tpl line 205 module and object files for stage 0 quicklybuilt



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-first.$(MELT_ZERO_GENERATED_FIRST_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-first+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_FIRST_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-first.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-first+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-first+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-first.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-first%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-first%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-first.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-base.$(MELT_ZERO_GENERATED_BASE_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-base+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_BASE_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-base.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-base+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-base+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-base.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-base%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-base%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-base.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-debug.$(MELT_ZERO_GENERATED_DEBUG_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-debug+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_DEBUG_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-debug.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-debug+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-debug+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-debug.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-debug%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-debug%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-debug.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-macro.$(MELT_ZERO_GENERATED_MACRO_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-macro+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_MACRO_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-macro.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-macro+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-macro+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-macro.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-macro%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-macro%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-macro.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-normal.$(MELT_ZERO_GENERATED_NORMAL_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-normal+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_NORMAL_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normal.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-normal+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-normal+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-normal.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-normal%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-normal%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normal.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-normatch.$(MELT_ZERO_GENERATED_NORMATCH_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-normatch+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_NORMATCH_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normatch.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-normatch+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-normatch+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-normatch.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-normatch%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-normatch%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-normatch.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-genobj.$(MELT_ZERO_GENERATED_GENOBJ_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-genobj+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_GENOBJ_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-genobj.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-genobj+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-genobj+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-genobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-genobj%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-genobj%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-genobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-outobj.$(MELT_ZERO_GENERATED_OUTOBJ_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-outobj+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_OUTOBJ_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-outobj.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-outobj+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-outobj+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-outobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-outobj%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-outobj%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-outobj.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



#@ from melt-newbuild.tpl line 209
melt-stage0-quicklybuilt/warmelt-modes.$(MELT_ZERO_GENERATED_MODES_CUMULMD5).quicklybuilt.meltmod.so: \
  melt-stage0-quicklybuilt/warmelt-modes+meltdesc.zpic.o $(addprefix melt-stage0-quicklybuilt/,$(addsuffix .quicklybuilt.zpic.o,$(MELT_ZERO_GENERATED_MODES_BASE)))
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-modes.meltmodule  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 212
	$(GCCMELT_LINKER) $(GCCMELT_LINKER_FLAGS) $(GCCMELT_SHARED_FLAGS) $(GCCMELT_LINKER_QUICKLYBUILT_FLAGS) -o $@ $^

melt-stage0-quicklybuilt/warmelt-modes+meltdesc.zpic.o: melt-stage0-quicklybuilt/warmelt-modes+meltdesc.c
	@echo @+@melt-newbuild-stamp zero-descriptor.warmelt-modes.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 216
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) -I $(^D) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_DESCRIPTOR_FLAGS) -c -o $@ $^

melt-stage0-quicklybuilt/warmelt-modes%.quicklybuilt.zpic.o: melt-stage0-quicklybuilt/warmelt-modes%.c $(melt_make_cc1_dependency)
	@echo @+@melt-newbuild-stamp zero-quicklybuilt.warmelt-modes.meltzpic  at= $@ left= $< circ= $^ from melt-newbuild.tpl line 220
	$(GCCMELT_COMPILER) $(GCCMELT_COMPILER_FLAGS) $(GCCMELT_PIC_FLAGS) $(GCCMELT_COMPILER_QUICKLYBUILT_FLAGS) -c -o $@ $<



## end stage 0 flavor quicklybuilt  from melt-newbuild.tpl line 225



#@ from melt-newbuild.tpl line 229 


## stage melt-stage1 from melt-newbuild.tpl line 232 





## melt_prevstage $(MELT_STAGE_ZERO) melt_prevflavor $(MELT_ZERO_FLAVOR)  from melt-newbuild.tpl line 243 

melt-stage1:
	test -d  melt-stage1/ || mkdir  melt-stage1


## stage melt-stage2 from melt-newbuild.tpl line 232 





## melt_prevstage melt-stage1 melt_prevflavor quicklybuilt  from melt-newbuild.tpl line 243 

melt-stage2:
	test -d  melt-stage2/ || mkdir  melt-stage2


## stage melt-stage3 from melt-newbuild.tpl line 232 





## melt_prevstage melt-stage2 melt_prevflavor quicklybuilt  from melt-newbuild.tpl line 243 

melt-stage3:
	test -d  melt-stage3/ || mkdir  melt-stage3


#@ from melt-newbuild.tpl line 249 eof melt-newbuild.mk
## eof melt-newbuild.mk generated from melt-newbuild.tpl & melt-newbuild.def
