/*  MELT file run-melt.h included in every generated file.
   all include files for generated code
   
   Copyright (C) 2008,2009 Free Software Foundation, Inc.
   Contributed by Basile Starynkevitch <basile@starynkevitch.net>

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.


GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.   If not see
<http://www.gnu.org/licenses/>.    */


/* all file including this are somehow plugins, perhaps MELT specific ones */
#include "gcc-plugin.h"


/* usual GCC middle-end includes, copied from melt-runtime.c */

#include "config.h"

/* this is intended to pass -DDISABLE_CHECKING explicitly */
#ifdef DISABLE_CHECKING
#undef ENABLE_CHECKING
#endif

#include "system.h"
#include "coretypes.h"
#include "obstack.h"
#include "tm.h"
#include "tree.h"
#include "gimple.h"
#include "filenames.h"
#include "tree-pass.h"
#include "tree-dump.h"
#include "tree-flow.h"
#include "tree-iterator.h"
#include "tree-inline.h"
#include "basic-block.h"
#include "timevar.h"
#include "ggc.h"
#include "cgraph.h"
#include "diagnostic.h"
#include "flags.h"
#include "toplev.h"
#include "options.h"
#include "params.h"
#include "real.h"
#include "prefix.h"
#include "md5.h"
#include "cppdefault.h"


/* MELT specific includes */


#include "ppl_c.h"
#include "melt-runtime.h"


#define meltcallcount -1

#define meltfptr  meltfram__.varptr
#define meltfnum  meltfram__.varnum
#define meltfclos meltfram__.clos
#define meltfrout meltfram__.clos->rout

/* these are added by the *melt-cc-script shell script */
extern const char melt_compiled_timestamp[];
extern const char melt_md5[];

/* this is generated by gengtype */
extern void gt_ggc_mx_melt_un (void*);

#if __GNUC__ >= 4
#define MELT_MODULE_VISIBILITY  __attribute__ ((visibility ("hidden")))
#else
#define MELT_MODULE_VISIBILITY
#endif

/* eof run-melt.h */
